/**
 * Executive Export Engine
 * 
 * Generates board-ready exports for insights, decisions, and executive briefs.
 * Formats: CSV, Markdown, structured JSON for downstream consumption.
 */

import type { AnalystFinding } from "./analysis-engine";

export interface ExportOptions {
  format: "csv" | "markdown" | "json";
  title: string;
  organizationName?: string;
  datasetName?: string;
  generatedAt?: string;
}

// ═══════════════════════════════════════════════════════
// INSIGHTS EXPORT
// ═══════════════════════════════════════════════════════

export function exportInsightsAsMarkdown(
  findings: AnalystFinding[],
  options: Omit<ExportOptions, "format">
): string {
  const lines: string[] = [];
  const date = options.generatedAt || new Date().toISOString().split("T")[0];
  
  lines.push(`# ${options.title}`);
  lines.push(`**Generated:** ${date}${options.organizationName ? ` | **Organization:** ${options.organizationName}` : ""}${options.datasetName ? ` | **Dataset:** ${options.datasetName}` : ""}`);
  lines.push(`**Findings:** ${findings.length} | **High Priority:** ${findings.filter(f => f.severity === "high").length}`);
  lines.push("");
  lines.push("---");
  lines.push("");
  
  // Executive summary
  const highFindings = findings.filter(f => f.severity === "high");
  if (highFindings.length > 0) {
    lines.push("## ⚠️ Critical Findings");
    lines.push("");
    for (const f of highFindings) {
      lines.push(`### ${f.title}`);
      lines.push(`- **Observation:** ${f.observation}`);
      lines.push(`- **Analysis:** ${f.inference}`);
      lines.push(`- **Recommendation:** ${f.recommendation}`);
      lines.push(`- **Decision Relevance:** ${f.decisionRelevance}`);
      lines.push(`- **Confidence:** ${f.confidence}% | **Method:** ${f.explain.method} | **Sample:** ${f.explain.sampleSize}`);
      if (f.pValue !== null) lines.push(`- **p-value:** ${f.pValue.toFixed(4)}`);
      lines.push("");
    }
  }
  
  const medFindings = findings.filter(f => f.severity === "medium");
  if (medFindings.length > 0) {
    lines.push("## 📊 Analytical Findings");
    lines.push("");
    for (const f of medFindings) {
      lines.push(`### ${f.title}`);
      lines.push(`- **Observation:** ${f.observation}`);
      lines.push(`- **Analysis:** ${f.inference}`);
      lines.push(`- **Recommendation:** ${f.recommendation}`);
      lines.push(`- **Confidence:** ${f.confidence}% | **Method:** ${f.explain.method}`);
      lines.push("");
    }
  }
  
  const infoFindings = findings.filter(f => f.severity === "info");
  if (infoFindings.length > 0) {
    lines.push("## ℹ️ Informational");
    lines.push("");
    for (const f of infoFindings) {
      lines.push(`- **${f.title}:** ${f.observation}`);
    }
    lines.push("");
  }
  
  // Methodology section
  lines.push("---");
  lines.push("## Methodology & Limitations");
  lines.push("");
  const methods = [...new Set(findings.map(f => f.explain.method))];
  lines.push(`**Methods used:** ${methods.join(", ")}`);
  lines.push("");
  const allLimitations = [...new Set(findings.flatMap(f => f.explain.limitations))];
  lines.push("**Limitations:**");
  for (const lim of allLimitations) {
    lines.push(`- ${lim}`);
  }
  lines.push("");
  lines.push("*This report was generated by Quantivis Decision Intelligence Platform. All findings are based on statistical analysis of provided data and should be validated by domain experts before informing strategic decisions.*");
  
  return lines.join("\n");
}

export function exportInsightsAsCSV(findings: AnalystFinding[]): string {
  const headers = [
    "Type", "Severity", "Title", "Observation", "Inference",
    "Recommendation", "Decision Relevance", "Confidence",
    "p-value", "Method", "Sample Size", "Metric Reference",
  ];
  
  const rows = findings.map(f => [
    f.type,
    f.severity,
    `"${f.title.replace(/"/g, '""')}"`,
    `"${f.observation.replace(/"/g, '""')}"`,
    `"${f.inference.replace(/"/g, '""')}"`,
    `"${f.recommendation.replace(/"/g, '""')}"`,
    `"${f.decisionRelevance.replace(/"/g, '""')}"`,
    f.confidence.toString(),
    f.pValue !== null ? f.pValue.toFixed(4) : "",
    `"${f.explain.method}"`,
    f.explain.sampleSize.toString(),
    `"${f.metricRef}"`,
  ]);
  
  return [headers.join(","), ...rows.map(r => r.join(","))].join("\n");
}

export function exportDecisionsAsCSV(decisions: Array<Record<string, unknown>>): string {
  const headers = [
    "ID", "Recommended Action", "Chosen Action", "Status",
    "Confidence", "Capped Confidence", "Decision Type",
    "Decided At", "Decided By", "Execution Status",
    "Predicted Impact", "Actual Value", "Outcome Delta",
  ];
  
  const rows = decisions.map(d => [
    d.id?.slice(0, 8) || "",
    `"${(d.recommended_action || "").replace(/"/g, '""')}"`,
    `"${(d.chosen_action || "").replace(/"/g, '""')}"`,
    d.decision_status || "",
    d.confidence_at_decision || "",
    d.capped_confidence || "",
    d.decision_type || "",
    d.decided_at || "",
    d.decided_by || "",
    d.execution_status || "",
    d.predicted_net_impact || "",
    d.actual_value || "",
    d.outcome_delta || "",
  ]);
  
  return [headers.join(","), ...rows.map(r => r.join(","))].join("\n");
}

// ═══════════════════════════════════════════════════════
// DOWNLOAD HELPER
// ═══════════════════════════════════════════════════════

export function downloadFile(content: string, filename: string, mimeType: string) {
  const blob = new Blob([content], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

export function exportAndDownload(
  data: AnalystFinding[],
  options: ExportOptions
) {
  const date = new Date().toISOString().split("T")[0];
  const baseName = `quantivis-${options.title.toLowerCase().replace(/\s+/g, "-")}-${date}`;
  
  switch (options.format) {
    case "markdown": {
      const content = exportInsightsAsMarkdown(data, options);
      downloadFile(content, `${baseName}.md`, "text/markdown");
      break;
    }
    case "csv": {
      const content = exportInsightsAsCSV(data);
      downloadFile(content, `${baseName}.csv`, "text/csv");
      break;
    }
    case "json": {
      const content = JSON.stringify({
        title: options.title,
        generated_at: date,
        organization: options.organizationName,
        dataset: options.datasetName,
        findings: data,
      }, null, 2);
      downloadFile(content, `${baseName}.json`, "application/json");
      break;
    }
  }
}
