import PptxGenJS from "pptxgenjs";

interface SlideData {
  title: string;
  subtitle?: string;
  bullets?: string[];
  table?: { headers: string[]; rows: string[][] };
  note?: string;
}

interface ExportOptions {
  companyName: string;
  reportTitle: string;
  date: string;
  slides: SlideData[];
  primaryColor?: string;
  accentColor?: string;
}

export async function exportToPowerPoint(options: ExportOptions) {
  const pptx = new PptxGenJS();
  const primary = options.primaryColor || "4F46E5";
  const accent = options.accentColor || "7C3AED";

  pptx.author = options.companyName;
  pptx.company = options.companyName;
  pptx.title = options.reportTitle;
  pptx.subject = `${options.reportTitle} — ${options.date}`;

  // Define master slide
  pptx.defineSlideMaster({
    title: "QUANTIVIS_MASTER",
    background: { color: "0F172A" },
    objects: [
      { rect: { x: 0, y: 0, w: "100%", h: 0.6, fill: { color: primary } } },
      {
        text: {
          text: options.companyName.toUpperCase(),
          options: { x: 0.5, y: 0.12, w: 4, h: 0.35, fontSize: 11, color: "FFFFFF", fontFace: "Arial", bold: true },
        },
      },
      {
        text: {
          text: options.date,
          options: { x: 7, y: 0.12, w: 2.5, h: 0.35, fontSize: 9, color: "FFFFFFCC", fontFace: "Arial", align: "right" },
        },
      },
    ],
  });

  // Title slide
  const titleSlide = pptx.addSlide();
  titleSlide.background = { color: "0F172A" };
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 0, w: "100%", h: "100%", fill: { color: "0F172A" } });
  titleSlide.addShape(pptx.ShapeType.rect, { x: 0, y: 2.2, w: "100%", h: 0.08, fill: { color: primary } });
  titleSlide.addText(options.reportTitle, { x: 0.8, y: 1.2, w: 8.5, h: 1, fontSize: 32, color: "FFFFFF", fontFace: "Arial", bold: true });
  titleSlide.addText(options.companyName, { x: 0.8, y: 2.5, w: 8.5, h: 0.6, fontSize: 18, color: accent, fontFace: "Arial" });
  titleSlide.addText(options.date, { x: 0.8, y: 3.2, w: 8.5, h: 0.5, fontSize: 14, color: "94A3B8", fontFace: "Arial" });
  titleSlide.addText("CONFIDENTIAL — BOARD USE ONLY", {
    x: 0.8, y: 4.5, w: 8.5, h: 0.4, fontSize: 10, color: "EF4444", fontFace: "Arial", bold: true,
  });

  // Content slides
  for (const slideData of options.slides) {
    const slide = pptx.addSlide({ masterName: "QUANTIVIS_MASTER" });

    slide.addText(slideData.title, {
      x: 0.5, y: 0.8, w: 9, h: 0.6, fontSize: 22, color: "FFFFFF", fontFace: "Arial", bold: true,
    });

    if (slideData.subtitle) {
      slide.addText(slideData.subtitle, {
        x: 0.5, y: 1.4, w: 9, h: 0.4, fontSize: 12, color: "94A3B8", fontFace: "Arial",
      });
    }

    const yPos = slideData.subtitle ? 2.0 : 1.6;

    if (slideData.bullets?.length) {
      slide.addText(
        slideData.bullets.map((b) => ({ text: b, options: { bullet: true, color: "CBD5E1", fontSize: 13 } })),
        { x: 0.7, y: yPos, w: 8.5, h: 3, fontFace: "Arial", paraSpaceAfter: 8 }
      );
    }

    if (slideData.table) {
      const headerRow = slideData.table.headers.map((h) => ({
        text: h,
        options: { bold: true, color: "FFFFFF", fill: { color: primary }, fontSize: 10, fontFace: "Arial" as const },
      }));
      const dataRows = slideData.table.rows.map((row) =>
        row.map((cell) => ({
          text: cell,
          options: { color: "CBD5E1", fontSize: 10, fontFace: "Arial" as const },
        }))
      );
      slide.addTable([headerRow, ...dataRows], {
        x: 0.5, y: yPos, w: 9,
        border: { type: "solid", pt: 0.5, color: "334155" },
        rowH: 0.35,
        colW: Array(slideData.table.headers.length).fill(9 / slideData.table.headers.length),
      });
    }

    if (slideData.note) {
      slide.addText(slideData.note, {
        x: 0.5, y: 4.8, w: 9, h: 0.4, fontSize: 8, color: "64748B", fontFace: "Arial", italic: true,
      });
    }
  }

  // Disclaimer slide
  const discSlide = pptx.addSlide({ masterName: "QUANTIVIS_MASTER" });
  discSlide.addText("Disclaimer", { x: 0.5, y: 0.8, w: 9, h: 0.6, fontSize: 22, color: "FFFFFF", fontFace: "Arial", bold: true });
  discSlide.addText(
    [
      "This report is generated by Quantivis Decision Intelligence Platform.",
      "All confidence scores are capped based on data volume and quality.",
      "AI-generated insights are probabilistic support tools — not fiduciary advice.",
      "Final decision accountability rests with executive leadership.",
      `Generated: ${options.date}`,
    ].join("\n\n"),
    { x: 0.7, y: 1.6, w: 8.5, h: 3, fontSize: 11, color: "94A3B8", fontFace: "Arial", paraSpaceAfter: 6 }
  );

  await pptx.writeFile({ fileName: `${options.reportTitle.replace(/\s+/g, "-").toLowerCase()}-${options.date}.pptx` });
}
