/**
 * Output Classification Badge — labels every intelligence output.
 *
 * Categories:
 * - OBSERVED_FACT: Directly from data, no inference
 * - STATISTICAL_INFERENCE: Model-derived from data
 * - HEURISTIC_ESTIMATE: Rule-based approximation
 * - AI_RECOMMENDATION: LLM/AI-generated advice
 */

import { Database, BarChart3, Cpu, Brain, Info } from "lucide-react";
import { Tooltip, TooltipContent, TooltipTrigger } from "@/components/ui/tooltip";

export type OutputClassification =
  | "OBSERVED_FACT"
  | "STATISTICAL_INFERENCE"
  | "HEURISTIC_ESTIMATE"
  | "AI_RECOMMENDATION";

const CONFIG: Record<OutputClassification, {
  label: string;
  description: string;
  icon: typeof Database;
  badgeClass: string;
}> = {
  OBSERVED_FACT: {
    label: "Observed Fact",
    description: "Directly computed from your data with no inference or estimation.",
    icon: Database,
    badgeClass: "bg-success/10 text-success border-success/20",
  },
  STATISTICAL_INFERENCE: {
    label: "Statistical Inference",
    description: "Derived from statistical analysis of your data. Subject to sample size and variance limitations.",
    icon: BarChart3,
    badgeClass: "bg-primary/10 text-primary border-primary/20",
  },
  HEURISTIC_ESTIMATE: {
    label: "Heuristic Estimate",
    description: "Rule-based approximation. Not model-calibrated. Treat as directional guidance only.",
    icon: Cpu,
    badgeClass: "bg-warning/10 text-warning border-warning/20",
  },
  AI_RECOMMENDATION: {
    label: "AI Recommendation",
    description: "Generated by AI from data context. Requires human judgment before acting.",
    icon: Brain,
    badgeClass: "bg-accent/50 text-accent-foreground border-accent/30",
  },
};

interface Props {
  classification: OutputClassification;
  compact?: boolean;
}

const OutputClassificationBadge = ({ classification, compact = false }: Props) => {
  const config = CONFIG[classification];
  const Icon = config.icon;

  if (compact) {
    return (
      <Tooltip>
        <TooltipTrigger asChild>
          <span className={`inline-flex items-center gap-1 text-[9px] font-bold uppercase tracking-wider px-1.5 py-0.5 rounded border cursor-help ${config.badgeClass}`}>
            <Icon className="w-2.5 h-2.5" />
            {config.label}
          </span>
        </TooltipTrigger>
        <TooltipContent side="bottom" className="max-w-[240px] text-xs">
          {config.description}
        </TooltipContent>
      </Tooltip>
    );
  }

  return (
    <div className={`inline-flex items-center gap-1.5 text-[10px] font-semibold px-2 py-1 rounded border ${config.badgeClass}`}>
      <Icon className="w-3 h-3" />
      <span className="uppercase tracking-wider">{config.label}</span>
      <Tooltip>
        <TooltipTrigger asChild>
          <Info className="w-2.5 h-2.5 opacity-60 cursor-help" />
        </TooltipTrigger>
        <TooltipContent side="bottom" className="max-w-[240px] text-xs">
          {config.description}
        </TooltipContent>
      </Tooltip>
    </div>
  );
};

export default OutputClassificationBadge;
