import { useState } from "react";
import { Button } from "@/components/ui/button";
import { Download, FileText, Loader2 } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

interface GovernanceExportData {
  maturityScore: number | null;
  maturityLevel: string;
  delta: number | null;
  strongest: [string, number] | null;
  weakest: [string, number] | null;
  stewardCount: number;
  retentionCount: number;
  risks: { label: string; severity: string }[];
  actions: { label: string }[];
  orgName: string;
}

const generateMarkdown = (d: GovernanceExportData): string => {
  const date = new Date().toISOString().split("T")[0];
  const lines: string[] = [];

  lines.push(`# Governance Summary — ${d.orgName}`);
  lines.push(`**Generated:** ${date}`);
  lines.push("");

  lines.push("## Governance Maturity");
  if (d.maturityScore !== null) {
    lines.push(`- **Score:** ${d.maturityScore}/100 (${d.maturityLevel})`);
    if (d.delta !== null) lines.push(`- **Trend:** ${d.delta > 0 ? "+" : ""}${d.delta} from previous assessment`);
    if (d.strongest) lines.push(`- **Strongest dimension:** ${d.strongest[0]} (${d.strongest[1]}%)`);
    if (d.weakest) lines.push(`- **Weakest dimension:** ${d.weakest[0]} (${d.weakest[1]}%)`);
  } else {
    lines.push("- No maturity assessment completed yet.");
  }
  lines.push("");

  lines.push("## Steward Coverage");
  lines.push(`- **Data Stewards assigned:** ${d.stewardCount}`);
  lines.push(`- **Status:** ${d.stewardCount >= 2 ? "Good coverage" : d.stewardCount >= 1 ? "Minimum viable" : "⚠ None assigned — high risk"}`);
  lines.push("");

  lines.push("## Retention Policy Coverage");
  lines.push(`- **Policies defined:** ${d.retentionCount}/6 categories`);
  lines.push(`- **Coverage:** ${Math.round((d.retentionCount / 6) * 100)}%`);
  lines.push("");

  lines.push("## Top Governance Risks");
  d.risks.forEach((r) => {
    lines.push(`- [${r.severity.toUpperCase()}] ${r.label}`);
  });
  lines.push("");

  lines.push("## Recommended Next Actions");
  d.actions.forEach((a, i) => {
    lines.push(`${i + 1}. ${a.label}`);
  });
  lines.push("");
  lines.push("---");
  lines.push(`*This report was generated by Quantivis Governance Engine on ${date}.*`);

  return lines.join("\n");
};

export const GovernanceExportButton = ({ data }: { data: GovernanceExportData }) => {
  const { toast } = useToast();
  const [exporting, setExporting] = useState(false);

  const handleExport = () => {
    setExporting(true);
    try {
      const md = generateMarkdown(data);
      const blob = new Blob([md], { type: "text/markdown;charset=utf-8" });
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `governance-summary-${new Date().toISOString().split("T")[0]}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      toast({ title: "Governance summary exported" });
    } catch {
      toast({ title: "Export failed", variant: "destructive" });
    } finally {
      setExporting(false);
    }
  };

  return (
    <Button size="sm" variant="outline" onClick={handleExport} disabled={exporting} className="gap-1.5 text-xs">
      {exporting ? <Loader2 className="w-3 h-3 animate-spin" /> : <Download className="w-3 h-3" />}
      Export Summary
    </Button>
  );
};

export default GovernanceExportButton;
