import { useState } from "react";
import { Button } from "@/components/ui/button";
import {
  DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuTrigger,
} from "@/components/ui/dropdown-menu";
import { Download, FileText, Loader2, ChevronDown } from "lucide-react";
import { useToast } from "@/hooks/use-toast";

export interface GovernanceExportData {
  maturityScore: number | null;
  maturityLevel: string;
  delta: number | null;
  strongest: [string, number] | null;
  weakest: [string, number] | null;
  stewardCount: number;
  retentionCount: number;
  risks: { label: string; severity: string }[];
  actions: { label: string }[];
  orgName: string;
}

const generateMarkdown = (d: GovernanceExportData): string => {
  const date = new Date().toISOString().split("T")[0];
  const lines: string[] = [];

  lines.push(`# Governance Summary — ${d.orgName}`);
  lines.push(`**Generated:** ${date}`);
  lines.push("");
  lines.push("## Governance Maturity");
  if (d.maturityScore !== null) {
    lines.push(`- **Score:** ${d.maturityScore}/100 (${d.maturityLevel})`);
    if (d.delta !== null) lines.push(`- **Trend:** ${d.delta > 0 ? "+" : ""}${d.delta} from previous assessment`);
    if (d.strongest) lines.push(`- **Strongest dimension:** ${d.strongest[0]} (${d.strongest[1]}%)`);
    if (d.weakest) lines.push(`- **Weakest dimension:** ${d.weakest[0]} (${d.weakest[1]}%)`);
  } else {
    lines.push("- No maturity assessment completed yet.");
  }
  lines.push("");
  lines.push("## Steward Coverage");
  lines.push(`- **Data Stewards assigned:** ${d.stewardCount}`);
  lines.push(`- **Status:** ${d.stewardCount >= 2 ? "Good coverage" : d.stewardCount >= 1 ? "Minimum viable" : "⚠ None assigned — high risk"}`);
  lines.push("");
  lines.push("## Retention Policy Coverage");
  lines.push(`- **Policies defined:** ${d.retentionCount}/6 categories`);
  lines.push(`- **Coverage:** ${Math.round((d.retentionCount / 6) * 100)}%`);
  lines.push("");
  lines.push("## Top Governance Risks");
  d.risks.forEach((r) => lines.push(`- [${r.severity.toUpperCase()}] ${r.label}`));
  lines.push("");
  lines.push("## Recommended Next Actions");
  d.actions.forEach((a, i) => lines.push(`${i + 1}. ${a.label}`));
  lines.push("");
  lines.push("---");
  lines.push(`*This report was generated by Quantivis Governance Engine on ${date}.*`);
  return lines.join("\n");
};

const generatePDFHtml = (d: GovernanceExportData): string => {
  const date = new Date().toISOString().split("T")[0];
  const riskBadge = (sev: string) =>
    sev === "high" ? "color:#ef4444;background:#fef2f2;border:1px solid #fecaca"
    : sev === "medium" ? "color:#f59e0b;background:#fffbeb;border:1px solid #fde68a"
    : "color:#10b981;background:#ecfdf5;border:1px solid #a7f3d0";

  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Governance Summary — ${d.orgName}</title>
<style>
  @page { size: A4; margin: 40px; }
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', system-ui, sans-serif; color: #1a1a2e; line-height: 1.6; max-width: 800px; margin: 0 auto; padding: 40px; }
  h1 { font-size: 22px; border-bottom: 2px solid #6366f1; padding-bottom: 8px; margin-bottom: 4px; }
  h2 { font-size: 15px; color: #4f46e5; margin-top: 28px; margin-bottom: 12px; text-transform: uppercase; letter-spacing: 0.5px; }
  .meta { font-size: 12px; color: #6b7280; margin-bottom: 24px; }
  .score-card { display: flex; gap: 24px; margin: 16px 0; }
  .score-item { padding: 16px; border: 1px solid #e5e7eb; border-radius: 8px; flex: 1; text-align: center; }
  .score-item .value { font-size: 28px; font-weight: 700; }
  .score-item .label { font-size: 11px; color: #6b7280; text-transform: uppercase; letter-spacing: 0.5px; margin-top: 4px; }
  .risk-item { padding: 8px 12px; margin: 6px 0; border-radius: 6px; font-size: 13px; display: flex; align-items: center; gap: 8px; }
  .risk-badge { padding: 2px 8px; border-radius: 4px; font-size: 10px; font-weight: 600; text-transform: uppercase; }
  .action-item { padding: 6px 0; font-size: 13px; border-bottom: 1px solid #f3f4f6; }
  .action-num { display: inline-block; width: 20px; height: 20px; background: #eef2ff; color: #4f46e5; border-radius: 4px; text-align: center; font-size: 11px; font-weight: 600; line-height: 20px; margin-right: 8px; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e5e7eb; font-size: 11px; color: #9ca3af; }
</style></head><body>
<h1>Governance Summary</h1>
<p class="meta">${d.orgName} — Generated ${date}</p>

<div class="score-card">
  <div class="score-item">
    <div class="value">${d.maturityScore !== null ? d.maturityScore : "—"}</div>
    <div class="label">Maturity Score /100</div>
    ${d.delta !== null ? `<div style="font-size:12px;color:${d.delta >= 0 ? "#10b981" : "#ef4444"};margin-top:4px">${d.delta > 0 ? "+" : ""}${d.delta} from previous</div>` : ""}
  </div>
  <div class="score-item">
    <div class="value">${d.stewardCount}</div>
    <div class="label">Data Stewards</div>
  </div>
  <div class="score-item">
    <div class="value">${d.retentionCount}/6</div>
    <div class="label">Retention Coverage</div>
  </div>
</div>

${d.strongest || d.weakest ? `
<h2>Dimension Analysis</h2>
<div class="score-card">
  ${d.strongest ? `<div class="score-item" style="border-color:#a7f3d0"><div class="value" style="color:#10b981">${d.strongest[1]}%</div><div class="label">Strongest: ${d.strongest[0]}</div></div>` : ""}
  ${d.weakest ? `<div class="score-item" style="border-color:#fecaca"><div class="value" style="color:#ef4444">${d.weakest[1]}%</div><div class="label">Weakest: ${d.weakest[0]}</div></div>` : ""}
</div>` : ""}

<h2>Top Governance Risks</h2>
${d.risks.map((r) => `<div class="risk-item"><span class="risk-badge" style="${riskBadge(r.severity)}">${r.severity}</span> ${r.label}</div>`).join("")}

<h2>Recommended Next Actions</h2>
${d.actions.map((a, i) => `<div class="action-item"><span class="action-num">${i + 1}</span>${a.label}</div>`).join("")}

<div class="footer">This report was generated by Quantivis Governance Engine on ${date}.</div>
</body></html>`;
};

const downloadFile = (content: string, filename: string, mimeType: string) => {
  const blob = new Blob([content], { type: `${mimeType};charset=utf-8` });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

const printPDF = (html: string) => {
  const printWindow = window.open("", "_blank");
  if (!printWindow) return false;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.onload = () => {
    printWindow.print();
  };
  return true;
};

export const GovernanceExportButton = ({ data }: { data: GovernanceExportData }) => {
  const { toast } = useToast();
  const [exporting, setExporting] = useState(false);

  const handleExport = (format: "markdown" | "pdf") => {
    setExporting(true);
    try {
      const date = new Date().toISOString().split("T")[0];
      if (format === "markdown") {
        downloadFile(generateMarkdown(data), `governance-summary-${date}.md`, "text/markdown");
        toast({ title: "Governance summary exported (Markdown)" });
      } else {
        const html = generatePDFHtml(data);
        const opened = printPDF(html);
        if (opened) {
          toast({ title: "PDF print dialog opened" });
        } else {
          // Fallback: download as HTML
          downloadFile(html, `governance-summary-${date}.html`, "text/html");
          toast({ title: "Downloaded as HTML — open and print to PDF" });
        }
      }
    } catch {
      toast({ title: "Export failed", variant: "destructive" });
    } finally {
      setExporting(false);
    }
  };

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button size="sm" variant="outline" disabled={exporting} className="gap-1.5 text-xs">
          {exporting ? <Loader2 className="w-3 h-3 animate-spin" /> : <Download className="w-3 h-3" />}
          Export
          <ChevronDown className="w-3 h-3" />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent align="end">
        <DropdownMenuItem onClick={() => handleExport("markdown")} className="text-xs gap-2">
          <FileText className="w-3.5 h-3.5" />
          Markdown (.md)
        </DropdownMenuItem>
        <DropdownMenuItem onClick={() => handleExport("pdf")} className="text-xs gap-2">
          <FileText className="w-3.5 h-3.5" />
          PDF (Print)
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  );
};

export default GovernanceExportButton;
